id: I2C696628
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T13:55:32+00:00'
last_modified: '2022-06-08T12:39:16.747358+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22264
  title: ཕར་ཕྱིན་མཐའ་དཔྱོད་མཁས་པའི་མགུལ་རྒྱན། ༼སེར་བྱེས་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4E82:
      image_group_id: I1KG22275
      title: ''
      total_pages: 836
      order: 1
      base_file: 4E82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
