id: P010310
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG22264
  title: ཕར་ཕྱིན་མཐའ་དཔྱོད་མཁས་པའི་མགུལ་རྒྱན། ༼སེར་བྱེས་པར་མ།༽
  author: ''
  volumes:
    abd0bf44f6454747bb4c270135b3f628:
      image_group_id: I1KG22275
      title: ''
      volume_number: 1
      total_pages: 836
      base_file: v001.txt
